// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
"use client";
import { Auth, getAuth } from "firebase/auth";
import { Firestore, getFirestore } from "firebase/firestore";
import { firebaseApp } from "@/firebase/config";
import { FirebaseProvider } from "@/firebase/provider";

interface FirebaseClientProviderProps {
  children: React.ReactNode;
}

export function FirebaseClientProvider({
  children,
}: FirebaseClientProviderProps) {
  // By initializing on the client, we ensure that the firebase instance is created only once.
  // This is an optimization to prevent unnecessarily re-initializing the firebase app.
  const auth = getAuth(firebaseApp);
  const firestore = getFirestore(firebaseApp);
  return (
    <FirebaseProvider
      firebaseApp={firebaseApp}
      auth={auth}
      firestore={firestore}
    >
      {children}
    </FirebaseProvider>
  );
}
