// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
// This file is used to initialize the Firebase app.
// It is not intended for direct use by the developer.
import { initializeApp, getApp, getApps, type FirebaseApp } from "firebase/app";

const firebaseConfig = {
    "apiKey": "AIzaSyD4hoy18alb6Kk6NDsmdEfepljPA7VHuds",
    "authDomain": "athkari-app-c88fa.firebaseapp.com",
    "projectId": "athkari-app-c88fa",
    "storageBucket": "athkari-app-c88fa.firebasestorage.app",
    "messagingSenderId": "258030956834",
    "appId": "1:258030956834:web:3d107f8786c7e1e16ef57b",
    "measurementId": "G-PJHJ9ZNPTB"
};

function createFirebaseApp(config: any): FirebaseApp {
  try {
    if (!getApps().length) {
      return initializeApp(config);
    }
    return getApp();
  } catch (e) {
    console.error("Failed to initialize Firebase", e);
    // Fallback for environments where initializeApp might fail during server-side rendering.
    // This is a temporary workaround.
    return {
      name: "fallback",
      options: {},
      automaticDataCollectionEnabled: false,
      delete: () => Promise.resolve(),
    } as unknown as FirebaseApp;
  }
}

export const firebaseApp = createFirebaseApp(firebaseConfig);
