// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
// This file is used to initialize the Firebase app.
// It is not intended for direct use by the developer.
import { initializeApp, getApp, getApps, FirebaseApp } from "firebase/app";

const firebaseConfig = {
    "apiKey": "your-api-key",
    "authDomain": "your-auth-domain",
    "projectId": "your-project-id",
    "storageBucket": "your-storage-bucket",
    "messagingSenderId": "your-messaging-sender-id",
    "appId": "your-app-id"
};

function createFirebaseApp(config: any): FirebaseApp {
  try {
    if (!getApps().length) {
      return initializeApp(config);
    }
    return getApp();
  } catch (e) {
    console.error("Failed to initialize Firebase", e);
    // Fallback for environments where initializeApp might fail during server-side rendering.
    // This is a temporary workaround.
    return {
      name: "fallback",
      options: {},
      automaticDataCollectionEnabled: false,
      delete: () => Promise.resolve(),
    } as unknown as FirebaseApp;
  }
}

export const firebaseApp = createFirebaseApp(firebaseConfig);
