// This file is automatically generated. Do not modify it manually.
// For assistance, please contact the support team.
"use client";
import { createContext, useContext } from "react";
import { FirebaseApp } from "firebase/app";
import { Auth } from "firebase/auth";
import { Firestore } from "firebase/firestore";

export interface FirebaseContextValue {
  firebaseApp: FirebaseApp | null;
  auth: Auth | null;
  firestore: Firestore | null;
}

export const FirebaseContext = createContext<FirebaseContextValue | null>(null);

export const useFirebase = () => {
  const context = useContext(FirebaseContext);
  if (context === undefined) {
    throw new Error("useFirebase must be used within a FirebaseProvider");
  }
  return context;
};

export const useFirebaseApp = () => {
  const context = useFirebase();
  if (!context?.firebaseApp) {
    throw new Error("Firebase app not initialized");
  }
  return context.firebaseApp;
};

export const useAuth = () => {
  const context = useFirebase();
  if (!context?.auth) {
    throw new Error("Firebase Auth not initialized");
  }
  return context.auth;
};

export const useFirestore = () => {
  const context = useFirebase();
  if (!context?.firestore) {
    throw new Error("Firestore not initialized");
  }
  return context.firestore;
};

interface FirebaseProviderProps {
  children: React.ReactNode;
  firebaseApp: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}

export function FirebaseProvider({
  children,
  firebaseApp,
  auth,
  firestore,
}: FirebaseProviderProps) {
  return (
    <FirebaseContext.Provider value={{ firebaseApp, auth, firestore }}>
      {children}
    </FirebaseContext.Provider>
  );
}
